services:
  language-app:
    image: registry.rimori.se/language/rimori-ui:0.2.2
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3100:3000"
  rimori-plugins:
    image: registry.rimori.se/language/rimori-plugins:0.2.2
    build:
      context: ./_plugins
      dockerfile: ./Dockerfile
    ports:
      - "3101:80"
